export const WORKER_QUEUE_NAMES = Symbol('WORKER_QUEUE_NAMES');
export const SYNTHETIC_STAGES_ENABLED = Symbol('SYNTHETIC_STAGES_ENABLED');
export const WORKER_S3_CONFIG = Symbol('WORKER_S3_CONFIG');
export const WORKER_SHAREPOINT_CONFIG = Symbol('WORKER_SHAREPOINT_CONFIG');
